name: Create PR
description: foo
author: Nicholas Valentinus
branding:
  icon: tool
  color: orange

inputs:
  git_name:
    description: 
    required: true
  git_email:
    description: 
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        
        ## dev-docs: GitHub Action has `set -e` auto-enabled; below, we will disable that.
        set +e

        ## dev-docs: i think it would be better to use a date format instead of a random hex as a UID
        # uid=$(openssl rand -hex 3)  # Random hex (6 chars)
        uid=$(date +'%Y%m%d_%H%M%S')

        branch="action-create-PR-$uid"

        git checkout -b $branch

        git config user.name "${{ inputs.git_name }}"
        git config user.email "${{ inputs.git_email }}"
        
        git add .
        git commit -m "foo bar baz"

        ## Handle the case where users didn't make any changes
        if [ $? -eq 1 ]; then
          echo "ERROR: Oops! You need to make some changes before creating a pull request."
          exit 1
        fi

        git push origin $branch

        gh pr create -f
      shell: bash