name: Quick PR
description: Simple GH Action to create a PR for single-commit changes
author: Nicholas Valentinus
branding:
  icon: cpu
  color: orange

inputs:
  git_name:
    description: The default value is your GitHub username.
    required: false
    default: ${{ github.actor }}
  git_email:
    description: The default value is USERNAME@users.noreply.github.com .
    required: false
    default: ${{ github.actor }}@users.noreply.github.com
  PR_title:
    description: The commit message, which is also the PR title.
    required: false

runs:
  using: 'composite'
  steps:
    - run: |
        ## 🚀🚀🚀
        set +e  # This lets us handle non-zero exits

        if [ -z "$(git status --porcelain)" ]; then
          echo "ERROR: Oops! You need to make some changes before creating a pull request."
          exit 1
        fi

        git config user.name "${{ inputs.git_name }}"
        git config user.email "${{ inputs.git_email }}"

        branch="action-create-PR-$(date +'%Y%m%d_%H%M%S')"
        git checkout -b $branch

        git add .

        ## Handle empty commit messages (as commits require messages)
        msg="${{ inputs.PR_title }}"
        if [ -z "$msg" ]; then
          msg="Review changes in $(git diff --cached --name-only | wc -l) files."
        fi

        git commit -m "$msg"

        git push origin $branch

        ## TODO: Find a way for users to use this action without manually checking the checkbox in settings
        gh pr create -f
        if [ $? -eq 1 ]; then
          echo "ERROR: Oops! You need to allow GitHub Actions to create a PR by checking the checkbox 'Allow GitHub Actions to create and approve pull requests' at https://github.com/$GITHUB_REPOSITORY/settings/actions ."
          exit 1
        fi
      shell: bash
