name: Create PR
description: foo
author: Nicholas Valentinus
branding:
  icon: tool
  color: orange

inputs:
  foo:
    description: 
    required: false

runs:
  using: 'composite'
  steps:
    - run: |
        
        uid=$(openssl rand -hex 3)  # Random hex (6 chars)
        
        git checkout -b action-create-PR-$uid
        git branch
      shell: bash